# Generated by Django 3.2.25 on 2024-09-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredientS',
            new_name='ingredients',
        ),
    ]
